In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('/content/updated_price_tracking_data (3).csv')

In [4]:
df.info

<bound method DataFrame.info of         Unnamed: 0                                               name  \
0                0  Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...
1                1  LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...
2                2  LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...
3                3  LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...
4                4  Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...
...            ...                                                ...
349749         294  PALOMINO 5 Layer Shelf Wall Mount Kitchen Uten...
349750         295  Smily Kiddos | Dual Slot Lunch Bag Unicorn The...
349751         296  Home Centre BARBADOS-MILFORD-26 Plastic Canist...
349752         297  ARECA Polyurethane Lunch Bag for Carry Lunch B...
349753         298  JUGTE Water Bottle for Kids Stainless Steel Bo...

         main_category                  sub_category  \
0           appliances              Air Conditioners
1           appliances              Air Conditioners
2           appliances              Air Conditioners
3           appliances              Air Conditioners
4           appliances              Air Conditioners
...                ...                           ...
349749  home & kitchen  Kitchen Storage & Containers
349750  home & kitchen  Kitchen Storage & Containers
349751  home & kitchen  Kitchen Storage & Containers
349752  home & kitchen  Kitchen Storage & Containers
349753             NaN                           NaN

                                                    image  \
0       https://m.media-amazon.com/images/I/31UISB90sY...
1       https://m.media-amazon.com/images/I/51JFb7FctD...
2       https://m.media-amazon.com/images/I/51JFb7FctD...
3       https://m.media-amazon.com/images/I/51JFb7FctD...
4       https://m.media-amazon.com/images/I/41lrtqXPiW...
...                                                   ...
349749  https://m.media-amazon.com/images/I/51ZuZCICne...
349750  https://m.media-amazon.com/images/I/81MWglMP5Z...
349751  https://m.media-amazon.com/images/I/61rR+L+pqI...
349752  https://m.media-amazon.com/images/I/71Kn-PASSe...
349753                                                NaN

                                                     link ratings  \
0       https://www.amazon.in/Lloyd-Inverter-Convertib...     4.2
1       https://www.amazon.in/LG-Convertible-Anti-Viru...     4.2
2       https://www.amazon.in/LG-Inverter-Convertible-...     4.2
3       https://www.amazon.in/LG-Convertible-Anti-Viru...       4
4       https://www.amazon.in/Carrier-Inverter-Split-C...     4.1
...                                                   ...     ...
349749  https://www.amazon.in/PALOMINO-Kitchen-Utensil...     4.2
349750  https://www.amazon.in/Smily-Kiddos-Teenagers-C...     4.4
349751  https://www.amazon.in/Home-Centre-Barbados-Tra...     4.4
349752  https://www.amazon.in/ARECA-Lunch-Office-Picni...     4.2
349753                                                NaN     NaN

       no_of_ratings discount_price actual_price  discounted_price_1  \
0              2,255        ₹32,999      ₹58,990            29829.21
1              2,948        ₹46,490      ₹75,990            42837.77
2              1,206        ₹34,490      ₹61,990            32148.38
3                 69        ₹37,990      ₹68,990            36756.03
4                630        ₹34,490      ₹67,790            33369.78
...              ...            ...          ...                 ...
349749            68         ₹2,835       ₹5,999             2577.94
349750           174           ₹945       ₹1,350              878.04
349751           223            NaN         ₹499              550.91
349752            72           ₹349       ₹1,299              337.34
349753           NaN            NaN          NaN                 NaN

        discounted_price_2  discounted_price_3  discounted_price_4  \
0                 31760.38            30613.93            29982.57
1                 43188.34            42348.83            43495.38
2                 32416.49            33400.09            32348.33
3                 35119.70            36901.56            36012.38
4                 33125.05            31979.98            32053.54
...                    ...                 ...                 ...
349749             2673.72             2588.11             2765.41
349750              889.27              851.06              897.11
349751              331.08              331.40              553.16
349752              330.93              334.92              331.85
349753                 NaN                 NaN                 NaN

        discounted_price_5  discounted_price_6  discounted_price_7
0                 30601.39            30687.30            31990.39
1                 43747.93            42096.26            45454.31
2                 32616.91            32438.23            31324.55
3                 35124.83            35540.26            36874.50
4                 33387.97            31744.14            33264.85
...                    ...                 ...                 ...
349749             2670.27             2703.53             2594.83
349750              852.26              886.94              851.16
349751               73.68              572.93              101.76
349752              337.82              332.35              318.12
349753                 NaN                 NaN                 NaN

[349754 rows x 17 columns]>

In [5]:
df.describe()

,Unnamed: 0,discounted_price_1,discounted_price_2,discounted_price_3,discounted_price_4,discounted_price_5,discounted_price_6,discounted_price_7
count,349754.000000,349753.000000,349753.000000,349753.000000,349753.000000,349753.000000,349753.000000,349753.000000
mean,6939.586189,2639.911740,2617.576360,2617.905752,2640.438695,2593.592648,2642.304533,2596.849233
std,5666.826418,9445.154188,9450.089446,9453.341945,9440.523471,9456.696266,9448.217952,9467.099900
min,0.000000,7.540000,7.520000,7.240000,7.720000,7.280000,7.830000,7.640000
25%,1591.000000,374.350000,325.820000,326.440000,374.310000,284.190000,374.080000,284.250000
50%,5910.000000,574.660000,557.440000,557.580000,581.210000,557.560000,594.460000,557.830000
75%,11181.000000,1290.660000,1291.440000,1290.890000,1291.870000,1291.670000,1291.240000,1291.020000
max,19199.000000,465875.980000,484969.150000,485911.890000,460243.300000,470508.170000,481479.960000,487944.180000

In [6]:
df.head(10)

,Unnamed: 0,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price,discounted_price_1,discounted_price_2,discounted_price_3,discounted_price_4,discounted_price_5,discounted_price_6,discounted_price_7
0,0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/31UISB90sY...,https://www.amazon.in/Lloyd-Inverter-Convertib...,4.2,"2,255","₹32,999","₹58,990",29829.21,31760.38,30613.93,29982.57,30601.39,30687.30,31990.39
1,1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.2,"2,948","₹46,490","₹75,990",42837.77,43188.34,42348.83,43495.38,43747.93,42096.26,45454.31
2,2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Inverter-Convertible-...,4.2,"1,206","₹34,490","₹61,990",32148.38,32416.49,33400.09,32348.33,32616.91,32438.23,31324.55
3,3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4,69,"₹37,990","₹68,990",36756.03,35119.70,36901.56,36012.38,35124.83,35540.26,36874.50
4,4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/41lrtqXPiW...,https://www.amazon.in/Carrier-Inverter-Split-C...,4.1,630,"₹34,490","₹67,790",33369.78,33125.05,31979.98,32053.54,33387.97,31744.14,33264.85
5,5,Voltas 1.4 Ton 3 Star Inverter Split AC(Copper...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/41TuyxwZ9m...,https://www.amazon.in/Voltas-Adjustable-173V-V...,4,"1,666","₹31,990","₹70,990",31201.55,31234.89,29538.08,31320.84,29878.75,29540.50,29128.83
6,6,Lloyd 1.0 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/31IXlxIPsO...,https://www.amazon.in/Lloyd-Inverter-Convertib...,4.2,"1,097","₹29,999","₹49,990",27320.27,27544.46,29237.84,28275.05,28688.99,27487.04,27065.44
7,7,Lloyd 1.5 Ton 5 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/31IXlxIPsO...,https://www.amazon.in/Lloyd-Inverter-Convertib...,4.3,"1,494","₹39,990","₹67,990",37267.11,36083.39,37353.34,38216.46,37959.92,36575.98,37999.22
8,8,Carrier 1 Ton 3 Star AI Flexicool Inverter Spl...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51sTXvsanQ...,https://www.amazon.in/Carrier-Flexicool-Invert...,4.1,674,"₹30,990","₹58,190",28614.75,28512.35,30311.16,28031.87,28203.09,28244.61,29692.83
9,9,"Voltas 1.5 Ton, 5 Star, Inverter Split AC(Copp...",appliances,Air Conditioners,https://m.media-amazon.com/images/I/51WQ3nWF0v...,https://www.amazon.in/Voltas-Inverter-Split-Co...,4,801,"₹37,999","₹73,990",37176.44,34887.17,34777.51,34675.57,36462.90,34662.79,36759.95

In [7]:
df.isna().sum()

Unnamed: 0                 0
name                       0
main_category              1
sub_category               1
image                      1
link                       1
ratings               107618
no_of_ratings         107618
discount_price         33264
actual_price           11068
discounted_price_1         1
discounted_price_2         1
discounted_price_3         1
discounted_price_4         1
discounted_price_5         1
discounted_price_6         1
discounted_price_7         1
dtype: int64

In [8]:
# Convert price and ratings-related columns to numeric values
def clean_numeric(column):
    return pd.to_numeric(df[column].astype(str).str.replace("₹", "").str.replace(",", ""), errors='coerce')

df["ratings"] = clean_numeric("ratings")
df["no_of_ratings"] = clean_numeric("no_of_ratings")
df["discount_price"] = clean_numeric("discount_price")
df["actual_price"] = clean_numeric("actual_price")

In [13]:
# Fill missing values for ratings and number of ratings with mean
df["ratings"].fillna(df["ratings"].mean(), inplace=True)
df["no_of_ratings"].fillna(df["no_of_ratings"].mean(), inplace=True)

<ipython-input-13-a92aa78c61fb>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["ratings"].fillna(df["ratings"].mean(), inplace=True)
<ipython-input-13-a92aa78c61fb>:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["ratings"].fillna(df["ratings"].mean(), inplace=True)
<ipython-input-13-a92aa78c61fb>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["no_of_ratings"].fillna(df["no_of_ratings"].mean(), inplace=True)
<ipython-input-13-a92aa78c61fb>:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["no_of_ratings"].fillna(df["no_of_ratings"].mean(), inplace=True)

In [14]:
# Fill missing values for discount_price and actual_price based on each other
df["discount_price"].fillna(df["actual_price"], inplace=True)
df["actual_price"].fillna(df["discount_price"], inplace=True)

<ipython-input-14-a70d12d6decb>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["discount_price"].fillna(df["actual_price"], inplace=True)
<ipython-input-14-a70d12d6decb>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["actual_price"].fillna(df["discount_price"], inplace=True)

In [15]:
# Drop unnecessary columns
df.drop(columns=["Unnamed: 0", "image", "link"], inplace=True)

In [17]:
# Save the preprocessed dataset
preprocessed_file_path = "/content/price_tracking_data.csv"
df.to_csv(preprocessed_file_path, index=False)